# -*- coding: utf-8 -*-
"""Part - 1 Tensor Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CbKU3F4XOqQsltuBl5mblkFM3r9Hu_D

# Tensor :- Tensors are Multi Dimensional Arrays

An Array is an ordered arrangement of numbers
"""

import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

#tensor with value 4 with no shape

tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

#tensor with 3 values . 1D tensor all integer values

tensor_one_d_float = tf.constant([2,0,-3,0.8])
print(tensor_one_d_float)

# 1D tensor with type float

tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6]
    ])
print(tensor_two_d)

tensor_three_d=tf.constant([
 [[1,2,0],
 [3,5,-1]],

[[4,5,6],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
])
print(tensor_three_d)

print(tensor_three_d.shape)

tensor_four_d = tf.constant([
[
 [[1,2,0],
 [3,5,-1]],

[[4,5,6],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
],
[
 [[10,20,0],
 [3,5,-1]],

[[40,50,60],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
],

[
 [[100,200,0],
 [3,5,-100]],

[[40,50,60],
 [7,-8,9]],

[[10,11,12],
 [13,-14,15]],

 [[16,17,18],
 [13,-14,15]]
]])

print(tensor_four_d)